# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "test"
  config.vm.network "private_network", ip: "192.168.33.10"
  # private networkに設定したIPでSSHするためにnetwokrkを再起動
  # OS毎にネットワーク再起動のコマンドを変更すること。
  config.vm.provision "shell", inline: <<-SHELL
      systemctl restart network
  SHELL
end
